export enum foodCategory {
    american = "american",
    asian = "asian",
    burgers = "burgers",
    chinese = "chinese",
    desserts = "desserts",
    fish = "fish",
    fusion = "fusion",
    greek = "greek",
    grill = "grill",
    gyros = "gyros",
    hungarian = "hungarian",
    indian = "indian",
    italian = "italian",
    japan = "japan",
    mexican = "mexican",
    middleEast = "middleEast",
    na = "na",
    pasta = "pasta",
    pizza = "pizza",
    salad = "salad",
    sandwich = "sandwich",
    soup = "soup",
    sushi = "sushi",
    thai = "thai",
    turkish = "turkish",
    vegan = "vegan",
}